algoritmo "atividade 3"

//lista de atividades

var

 n1 : real
 n2 : real

inicio
escreva("digite o primeiro numero: ")
leia(n1)
   escreva("digite um segundo numero: ")
   leia(n2)

    SE n1>n2 ENTAO
    escreva(n1 , " é maior que " , n2)

    SENAO

    SE n1<n2 ENTAO
    escreva(n1 , " é menor que " , n2)

    SENAO

    SE n1=n2 ENTAO
    escreva (n1 , " é igual a " , n2)

    FIMSE
     FIMSE
      FIMSE

fimalgoritmo